services:
  node-api:
    image: dockerhub.codecks.io/cdx/node-api-u20:${CDX_VERSION:?set CDX_VERSION}
    depends_on:
      - db
    ports:
      - 9393:9393
    env_file:
      - .env
    environment:
      PSQL_HOSTNAME: db

  image-resizer:
    image: dockerhub.codecks.io/cdx/node-api-u20:${CDX_VERSION:?set CDX_VERSION}
    ports:
      - 9494:9494
    command: node node-api/build/docker/img-server.js
    environment:
      TRANSLATE_HOST: localhost:9000->minio:9000

  worker:
    image: dockerhub.codecks.io/cdx/node-api-u20:${CDX_VERSION:?set CDX_VERSION}
    command: node node-api/build/docker/jobs.js
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PSQL_HOSTNAME: db

  db:
    image: postgres:15
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PSQL_DB_NAME}
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}

  db-scripts:
    image: dockerhub.codecks.io/cdx/db-scripts:${CDX_VERSION:?set CDX_VERSION}
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PSQL_HOSTNAME: db
      PGPASSWORD: ${PSQL_PASSWORD}

  frontend:
    image:  dockerhub.codecks.io/cdx/frontend:${CDX_VERSION:?set CDX_VERSION}
    ports:
      - 8080:80
    environment:
      REACT_APP_API_HOST: ${API_HOST}
      REACT_APP_PUSH_HOST: ${PUSH_HOST}
      REACT_APP_IMG_RESIZER_HOST: ${IMG_RESIZER_HOST}
      REACT_APP_MAX_STORAGE_MBS: ${MAX_STORAGE_MBS}

  minio:
    image: minio/minio:latest
    volumes:
      - s3-data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    command: server /data

volumes:
  db-data:
  s3-data:
